### ISSUE TITLE
Prefpanes not applying

### ISSUE THREAD

**Issue by augustin-bv** [DocSystem/bigsur-icons-for-catalina#1]
Hello my dear DocSystem
Just let u know that the prefpanes are not theming even tough Ik its impossible to theme them
have a great day

**Comment by DocSystem** [comment]
There isn't a prefpanes apply system and if you know it is impossible, why create an issue? This issue will be closed.

**Comment by Vladimir-Moskalenko** [comment]
Solution: 
1. go to /System/Library/PreferencePanes
2. find the needed .prefPane file
3. go to its /Contents/Resources/
4. change the icon!
