### ISSUE TITLE
Where did you find these icons on Big Sur?

### ISSUE THREAD

**Issue by amomchilov** [DocSystem/bigsur-icons-for-catalina#4]
I could only find the plain blue/purple assets. Where did you find the other folder icons? https://developer.apple.com/forums/thread/657431?page=1#686636022

**Comment by DocSystem** [comment]
I created folders with their names and then copied their icons

**Comment by amomchilov** [comment]
Oh wow, I didn't realize it was that simple. I have some vague recolleciton of being unable to copy these "special" home folder icons.

Neat, thanks!
