### ISSUE TITLE
Excuse me?

### ISSUE THREAD

**Issue by Wizkid305** [DocSystem/bigsur-icons-for-catalina#5]
Um... sorry to bother you but do you know why the calendar icon is crooked and do you plan to fix this after adding more icons?
![Screen Shot 2021-09-15 at 5 24 05 PM](https://user-images.githubusercontent.com/90802219/133511622-e6f2d0fe-8019-447b-b730-a55b853473c3.png)

**Comment by DocSystem** [comment]
Sorry, but I don't plan to fix this bug... I already tried many times but nothing worked! If you want me to add more icons, tell me which ones and I will add them!

**Comment by Wizkid305** [comment]
oh well that's a shame but at least you tried. Although it would be cool if you could add the logic pro and final cut pro icons.

**Comment by Wizkid305** [comment]
oh i would also like to know if there was a way to change the icons within finder?

**Comment by DocSystem** [comment]
Yep! You can change icons using Finder!
* Copy the icns file
* Right click on the app and select ``Properties``
* Select the icon at top and then paste the icns (using Cmd+V)

**Comment by Wizkid305** [comment]
ok Thank you

**Comment by Wizkid305** [comment]
Oh I'm sorry I didn't mean finder I didn't notice. I meant to ask if there was a way to change the icons inside of the system preferences app?

**Comment by DocSystem** [comment]
Oh I see...
Unfortunately, no. I already tried changing system preferences icons, but nothing worked...

**Comment by Wizkid305** [comment]
oh ok that's alright just knowing that you tried most of the things I'm asking about makes it fine

**Comment by Wizkid305** [comment]
Thank you anyways though.
